// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject


package main

import (
	"gitee.com/geekbang/basic-go/webook/internal/repository"
	"gitee.com/geekbang/basic-go/webook/internal/repository/cache/local"
	"gitee.com/geekbang/basic-go/webook/internal/repository/dao"
	"gitee.com/geekbang/basic-go/webook/internal/service"
	local2 "gitee.com/geekbang/basic-go/webook/internal/service/sms/local"
	"gitee.com/geekbang/basic-go/webook/internal/web"
	"gitee.com/geekbang/basic-go/webook/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	store := ioc.InitRedisStore()
	v := ioc.InitMiddleWare(store)
	db := ioc.InitMysql()
	userDaoInterface := dao.NewUserDAO(db)
	userCache := local.NewUserCache()
	userRepository := repository.NewUserRepository(userDaoInterface, userCache)
	userService := service.NewUserService(userRepository)
	smsService := local2.NewLocalSmsService()
	smsCache := local.NewLocalSmsCache()
	codeRepository := repository.NewCodeRepository(smsCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService)
	engine := ioc.InitWeb(v, userHandler)
	return engine
}
