apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: webook
  name: mysql-pvc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

  
