apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: webook
  name: pv-local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"

  
