---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/8/24 15:38
---


local key = KEYS[1]
-- 用户验证的key
local verifyCode = ARGV[1]
-- 在redis 中的 验证码
local code = redis.call("get", key)

local keyCnt = key .. ":cnt"

-- keyCnt 不存在 的话  cnt  就 nil  可以用cnt == nil  来判断
local cnt = tonumber(redis.call("get",keyCnt))
if cnt == nil then
    -- 这个电话号码不存在 九成是攻击
    return -3

elseif cnt <= 0 then
    -- 用户一直输错验证码  大概率有人攻击
    return -1
elseif verifyCode == code then
    -- 用户输入正确,直接删除 避免复用
    redis.call("set",keyCnt,-1)
    return 0
else
    -- 用户输入错误
    -- 可验证次数 -1
    redis.call("decr", keyCnt)
    --redis.call("decr", keyCnt,-1)
    return -2
end
