---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/8/24 14:56
---


-- jey
local key = KEYS[1]
--验证码
local code = ARGV[1]
-- 过期时间
local explain = tonumber(ARGV[2])
-- 最小间隔
local betweenExp = tonumber(ARGV[3])
-- 设置累计错误尝试次数
local cntKey = key .. ":cnt"
local count = tonumber(ARGV[4])

local ttl = redis.call("TTL", key)
--The command returns -2 if the key does not exist.
--The command returns -1 if the key exists but has no associated expire.
if ttl == -1 then
    -- key 存在,但是没有过期时间
    return -2
elseif ttl == -2 or ttl < explain - betweenExp then
    --key 不存在  或者已经超过了 最短申请时间
    redis.call("SET", key, code)
    redis.call("EXPIRE", key, explain)

    redis.call("SET", cntKey, count)
    redis.call("EXPIRE", cntKey, explain)
    return 0

else
    -- 发送过于频繁
    return -1
end
