// Code generated by MockGen. DO NOT EDIT.
// Source: F:\git_push\webook\internal\web\jwt.go

// Package jwtmocks is a generated GoMock package.
package jwtmocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEncryptionHandle is a mock of EncryptionHandle interface.
type MockEncryptionHandle struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionHandleMockRecorder
}

// MockEncryptionHandleMockRecorder is the mock recorder for MockEncryptionHandle.
type MockEncryptionHandleMockRecorder struct {
	mock *MockEncryptionHandle
}

// NewMockEncryptionHandle creates a new mock instance.
func NewMockEncryptionHandle(ctrl *gomock.Controller) *MockEncryptionHandle {
	mock := &MockEncryptionHandle{ctrl: ctrl}
	mock.recorder = &MockEncryptionHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionHandle) EXPECT() *MockEncryptionHandleMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptionHandle) Decrypt(tokenStr, secretCode string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", tokenStr, secretCode)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptionHandleMockRecorder) Decrypt(tokenStr, secretCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptionHandle)(nil).Decrypt), tokenStr, secretCode)
}

// Encryption mocks base method.
func (m *MockEncryptionHandle) Encryption(arg0 map[string]string, arg1 string, arg2 time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encryption", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encryption indicates an expected call of Encryption.
func (mr *MockEncryptionHandleMockRecorder) Encryption(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encryption", reflect.TypeOf((*MockEncryptionHandle)(nil).Encryption), arg0, arg1, arg2)
}
