db.mysql:
  dsn: "root:r4t7u#8i9s@tcp(120.132.118.90:3306)/webook1"

redis:
  dsn: "webook-redis-service:6380"

kafka:
  addrs:
    - "localhost:9094"



#  使用etcd 最好使用这种
#
#mysql:
#  dsn: "root:root@tcp(webook-mysql-service:3308)/webook"
#
#redis1:
#  dsn: "webook-redis-service:6380"