// Code generated by MockGen. DO NOT EDIT.
// Source: F:\git_push\webook\internal\repository\cache\type.go

// Package cachemocks is a generated GoMock package.
package cachemocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/geekbang/basic-go/webook/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockSmsCache is a mock of SmsCache interface.
type MockSmsCache struct {
	ctrl     *gomock.Controller
	recorder *MockSmsCacheMockRecorder
}

// MockSmsCacheMockRecorder is the mock recorder for MockSmsCache.
type MockSmsCacheMockRecorder struct {
	mock *MockSmsCache
}

// NewMockSmsCache creates a new mock instance.
func NewMockSmsCache(ctrl *gomock.Controller) *MockSmsCache {
	mock := &MockSmsCache{ctrl: ctrl}
	mock.recorder = &MockSmsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSmsCache) EXPECT() *MockSmsCacheMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockSmsCache) GenerateKey(biz, phone string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey", biz, phone)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockSmsCacheMockRecorder) GenerateKey(biz, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockSmsCache)(nil).GenerateKey), biz, phone)
}

// Set mocks base method.
func (m *MockSmsCache) Set(ctx context.Context, biz, phone, code string, cnt int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, biz, phone, code, cnt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSmsCacheMockRecorder) Set(ctx, biz, phone, code, cnt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSmsCache)(nil).Set), ctx, biz, phone, code, cnt)
}

// Verify mocks base method.
func (m *MockSmsCache) Verify(ctx context.Context, biz, phone, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockSmsCacheMockRecorder) Verify(ctx, biz, phone, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockSmsCache)(nil).Verify), ctx, biz, phone, code)
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserCache) Get(ctx context.Context, id int64) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserCacheMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserCache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockUserCache) Set(ctx context.Context, u domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUserCacheMockRecorder) Set(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUserCache)(nil).Set), ctx, u)
}
