db:
  dsn: "root:root@tcp(localhost:13316)/webook_reward"

grpc:
  server:
    port: 8099
    etcdTTL: 60
  client:
    payment:
      target: "etcd:///service/payment"
    account:
      target: "etcd:///service/account"

etcd:
  endpoints:
    - "localhost:12379"